### ISSUE TITLE
can't clone the repo properly

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/bgc_synthesis#11]
Cloning into '/Users/myer056/Documents/GitHub/bgc_synthesis'...
remote: Enumerating objects: 775, done.        
remote: Counting objects: 100% (77/77), done.        
remote: Compressing objects: 100% (66/66), done.        
remote: Total 775 (delta 24), reused 56 (delta 11), pack-reused 698        
Receiving objects: 100% (775/775), 191.79 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (144/144), done.
Downloading data_NERR/cbv/meteorology/cbvtcmet2001.csv (4.6 MB)
Error downloading object: data_NERR/cbv/meteorology/cbvtcmet2001.csv (dfa47e8): Smudge error: Error downloading data_NERR/cbv/meteorology/cbvtcmet2001.csv (dfa47e843d37275e796d37e52a4dff9c4f8d8df0df81e3679e87e344e784e18e): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /Users/Myer056/OneDrive - PNNL/Documents/GitHub/bgc_synthesis/.git/lfs/logs/20210617T171421.890007.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: data_NERR/cbv/meteorology/cbvtcmet2001.csv: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?

**Comment by MattyD797** [comment]
git lfs seems to have a limit of 5GB of data. Tried adding my predicted values, but froze the repo. Working on removing these files.

**Comment by MattyD797** [comment]
Deleted data storage system. Cloning files will not work with lfs.
